### PR TITLE
Milestone 1 review

### PR DESCRIPTION
**Pull request by JSmith989**
## Description
As a team, worked together to finish the project that was handed to us so we will be able to start the next step. 

## Related Issue
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/18
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/27
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/25
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/14
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/16
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/70
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/28
https://github.com/nss-evening-cohort-13/pan-am-airlines-dashboard-pan-am-airlines-dashboard/issues/23

## Motivation and Context
The project that we inherited wasn't quite finished. We needed to finish it in order to start the next phase. 

## How Can This Be Tested?
https://fir-pan-am.web.app/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by drteresavasquez** [comment]
Your navbar does not work on mobile.

**Review by drteresavasquez — CHANGES_REQUESTED** [review]
Get the navbar working for mobile and I’ll test the UI

**Comment by JSmith989** [comment]
ah I see, we will fix that

**Review by drteresavasquez — APPROVED** [review]
Looks good

**Pull request merged**
