### PR TITLE
Update crew member flight

### PR DESCRIPTION
**Pull request by chris-calhoun**
## Description
Fixed bug where crew members weren't being removed from flight on update.

## Related Issue
#116 

## Motivation and Context
Updating crew members for a flight was not working. Crew members could only be added, not removed.

## How Can This Be Tested?
git fetch
git checkout updateCrewMemberFlightId

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by wppattonjr — APPROVED** [review]
👍🏿

**Comment by willkotheimer** [comment]
This has a bug in it. If I select pilots and crew from the dropdown and come back to the update screen the pilots show up in the crew section selected. If you want to make another bug I'll approve this one, so we can move forward though!

**Comment by willkotheimer** [comment]
Especially since we're not pushing to master yet!

**Comment by chris-calhoun** [comment]
Oh yeah, I wasn't solving that issue yet, just trying to make sure the correct members showed up on the flight card and on the update form dropdown.

**Comment by willkotheimer** [comment]
I see that its categorizing the crew on the display card, but the pilots still on update page as crew. If you want to fix that, that's fine. Or we can just work on it tonight if you want...

**Comment by willkotheimer** [comment]
Looks great!

**Review by willkotheimer — APPROVED** [review]

**Pull request merged**
